export const flightsFromQuito = [
  "Vuelos de Quito a Guayaquil",
  "Vuelos de Quito a Madrid",
  "Vuelos de Quito a São Paulo",
  "Vuelos de Quito a San José",
  "Vuelos de Quito a Washington D. C.",
  "Vuelos de Quito a Río de Janeiro",
  "Vuelos de Quito a París",
  "Vuelos de Quito a Nueva York",
  "Vuelos de Quito a Buenos Aires",
  "Vuelos de Quito a Medellín",
  "Vuelos de Quito a Lima",
  "Vuelos de Quito a Cartagena de Indias",
  "Vuelos de Quito a Ciudad de Guatemala",
  "Vuelos de Quito a Milán",
  "Vuelos de Quito a Bogotá",
  "Vuelos de Quito a Miami",
  "Vuelos de Quito a Londres",
  "Vuelos de Quito a Ciudad de México",
  "Vuelos de Quito a San Salvador",
  "Vuelos de Quito a Cancún",
];
